#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${1:-${ROOT_DIR}/.env.prod}"
OUTPUT_FILE="${2:-${ROOT_DIR}/compose.override.generated.yaml}"
GENERATE_SENSITIVE_CONFIGS_SCRIPT="${ROOT_DIR}/generate-sensitive-configs.sh"

require_file() {
  [[ -f "$1" ]] || {
    echo "Missing required file: $1" >&2
    exit 1
  }
}

load_env() {
  require_file "${ENV_FILE}"
  # shellcheck disable=SC1090
  set -a && . "${ENV_FILE}" && set +a
  : "${DEPLOY_ROOT:?DEPLOY_ROOT is required}"
}

append_service_header() {
  local service="$1"
  if [[ -z "${EMITTED_SERVICES[${service}]:-}" ]]; then
    {
      printf '  %s:\n' "${service}"
      printf '    volumes:\n'
    } >> "${OUTPUT_FILE}.tmp"
    EMITTED_SERVICES["${service}"]=1
  fi
}

append_mount_if_present() {
  local service="$1"
  local source="$2"
  local target="$3"

  if [[ -f "${source}" ]]; then
    append_service_header "${service}"
    printf '      - "%s:%s:ro"\n' "${source}" "${target}" >> "${OUTPUT_FILE}.tmp"
    MOUNT_COUNT=$((MOUNT_COUNT + 1))
  fi
}

load_env

if [[ -f "${GENERATE_SENSITIVE_CONFIGS_SCRIPT}" ]]; then
  bash "${GENERATE_SENSITIVE_CONFIGS_SCRIPT}" "${ENV_FILE}"
fi

declare -A EMITTED_SERVICES=()
MOUNT_COUNT=0

{
  printf '# Generated by generate-compose-overrides.sh. Do not edit by hand.\n'
  printf 'name: ${COMPOSE_PROJECT_NAME}\n'
  printf 'services:\n'
} > "${OUTPUT_FILE}.tmp"

append_mount_if_present gateway "${DEPLOY_ROOT}/control/overrides/GW/config/mcpTools.tsv" "/srv/dc/dc/GW/config/mcpTools.tsv"
append_mount_if_present gateway "${DEPLOY_ROOT}/control/overrides/GW/config/apiKeyList.csv" "/srv/dc/dc/GW/config/apiKeyList.csv"
append_mount_if_present gateway "${DEPLOY_ROOT}/control/overrides/GW/config/spring-gw-client.xml" "/srv/dc/dc/GW/config/spring-gw-client.xml"
append_mount_if_present gateway "${DEPLOY_ROOT}/control/overrides/GW/config/log4j.ini" "/srv/dc/dc/GW/config/log4j.ini"

append_mount_if_present mdsvr "${DEPLOY_ROOT}/control/overrides/MDSvr/config/log4j.ini" "/srv/dc/dc/MDSvr/config/log4j.ini"
append_mount_if_present apssvr "${DEPLOY_ROOT}/control/overrides/APSSvr/config/log4j.ini" "/srv/dc/dc/APSSvr/config/log4j.ini"
append_mount_if_present apssvr "${DEPLOY_ROOT}/control/overrides/APSSvr/config/application.properties" "/srv/dc/dc/APSSvr/config/application.properties"
append_mount_if_present quantsvr "${DEPLOY_ROOT}/control/overrides/QuantSvr/config/log4j.ini" "/srv/dc/dc/QuantSvr/config/log4j.ini"
append_mount_if_present quantsvr "${DEPLOY_ROOT}/control/overrides/QuantSvr/config/application.properties" "/srv/dc/dc/QuantSvr/config/application.properties"
append_mount_if_present indsvr "${DEPLOY_ROOT}/control/overrides/INDSvr/config/log4j.ini" "/srv/dc/dc/INDSvr/config/log4j.ini"
append_mount_if_present indsvr "${DEPLOY_ROOT}/control/overrides/INDSvr/config/application.properties" "/srv/dc/dc/INDSvr/config/application.properties"
append_mount_if_present simsvr "${DEPLOY_ROOT}/control/overrides/SIMSvr/config/log4j.ini" "/srv/dc/dc/SIMSvr/config/log4j.ini"
append_mount_if_present batchsvr "${DEPLOY_ROOT}/control/overrides/BatchSvr/config/log4j.ini" "/srv/dc/dc/BatchSvr/config/log4j.ini"
append_mount_if_present batchsvr "${DEPLOY_ROOT}/control/overrides/BatchSvr/config/application.properties" "/srv/dc/dc/BatchSvr/config/application.properties"

if [[ "${MOUNT_COUNT}" -eq 0 ]]; then
  {
    printf '# Generated by generate-compose-overrides.sh. Do not edit by hand.\n'
    printf '# No optional override files were found under ${DEPLOY_ROOT}/control/overrides.\n'
    printf 'name: ${COMPOSE_PROJECT_NAME}\n'
    printf 'services: {}\n'
  } > "${OUTPUT_FILE}.tmp"
fi

mv "${OUTPUT_FILE}.tmp" "${OUTPUT_FILE}"
echo "Generated ${OUTPUT_FILE} with ${MOUNT_COUNT} optional override mount(s)."
