#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${1:-${ROOT_DIR}/.env.prod}"
OUTPUT_FILE="${2:-${ROOT_DIR}/compose.override.generated.yaml}"
COMPOSE_FILE="${ROOT_DIR}/compose.yaml"
GENERATE_SENSITIVE_CONFIGS_SCRIPT="${ROOT_DIR}/generate-sensitive-configs.sh"
VALIDATE_ENV_SCRIPT="${ROOT_DIR}/validate-env.sh"

CONFIG_SERVICES=(
  gateway
  loginsvr
  mdsvr
  apssvr
  quantsvr
  indsvr
  simsvr
  batchsvr
)

require_file() {
  [[ -f "$1" ]] || {
    echo "Missing required file: $1" >&2
    exit 1
  }
}

load_env() {
  require_file "${ENV_FILE}"
  require_file "${COMPOSE_FILE}"
  require_file "${VALIDATE_ENV_SCRIPT}"
  bash "${VALIDATE_ENV_SCRIPT}" "${ENV_FILE}"
  # shellcheck disable=SC1090
  set -a && . "${ENV_FILE}" && set +a
  : "${DEPLOY_ROOT:?DEPLOY_ROOT is required}"
}

config_name_for_service() {
  case "$1" in
    gateway) printf 'GW\n' ;;
    loginsvr) printf 'LoginSvr\n' ;;
    mdsvr) printf 'MDSvr\n' ;;
    apssvr) printf 'APSSvr\n' ;;
    quantsvr) printf 'QuantSvr\n' ;;
    indsvr) printf 'INDSvr\n' ;;
    simsvr) printf 'SIMSvr\n' ;;
    batchsvr) printf 'BatchSvr\n' ;;
    *)
      echo "Unsupported config service: $1" >&2
      return 1
      ;;
  esac
}

resolve_service_image() {
  local service="$1"
  awk -v service="${service}" '
    $0 == "  " service ":" {
      in_service = 1
      next
    }
    in_service && /^  [[:alnum:]_-]+:$/ {
      exit
    }
    in_service && $1 == "image:" {
      print $2
      exit
    }
  ' <<< "${BASE_COMPOSE_CONFIG}"
}

seed_service_config() {
  local service="$1"
  local config_name image_ref temp_container staging_dir source_dir target_dir

  config_name="$(config_name_for_service "${service}")"
  image_ref="$(resolve_service_image "${service}")"
  [[ -n "${image_ref}" ]] || {
    echo "Could not resolve Docker image for service ${service}." >&2
    return 1
  }

  temp_container="dc-config-seed-${service}-$$-${RANDOM}"
  staging_dir="$(mktemp -d)"
  source_dir="/srv/dc/dc/${config_name}/config"
  target_dir="${DEPLOY_ROOT}/control/overrides/${config_name}/config"

  if ! docker create --name "${temp_container}" "${image_ref}" >/dev/null; then
    rm -rf "${staging_dir}"
    echo "Could not create temporary container from ${image_ref}." >&2
    return 1
  fi

  if ! docker cp "${temp_container}:${source_dir}/." "${staging_dir}/" >/dev/null; then
    docker rm -f "${temp_container}" >/dev/null 2>&1 || true
    rm -rf "${staging_dir}"
    echo "Could not read ${source_dir} from image ${image_ref}." >&2
    return 1
  fi

  docker rm "${temp_container}" >/dev/null 2>&1 || true

  if ! find "${staging_dir}" -mindepth 1 -print -quit | grep -q .; then
    rm -rf "${staging_dir}"
    echo "Image ${image_ref} has an empty config directory at ${source_dir}." >&2
    return 1
  fi

  mkdir -p "${target_dir}"
  # Image defaults only fill missing paths. Existing operator overrides are never overwritten.
  cp -a -n "${staging_dir}/." "${target_dir}/"
  rm -rf "${staging_dir}"

  echo "Prepared full config override directory for ${config_name}: ${target_dir}"
}

seed_all_service_configs() {
  local service

  echo "Ensuring application images are available for config extraction."
  docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" pull "${CONFIG_SERVICES[@]}"

  BASE_COMPOSE_CONFIG="$(
    docker compose --env-file "${ENV_FILE}" -f "${COMPOSE_FILE}" config
  )"

  for service in "${CONFIG_SERVICES[@]}"; do
    seed_service_config "${service}"
  done
}

append_service_header() {
  local service="$1"
  if [[ -z "${EMITTED_SERVICES[${service}]:-}" ]]; then
    {
      printf '  %s:\n' "${service}"
      printf '    volumes:\n'
    } >> "${OUTPUT_FILE}.tmp"
    EMITTED_SERVICES["${service}"]=1
  fi
}

append_config_dir_mount() {
  local service="$1"
  local config_name="$2"
  local source="${DEPLOY_ROOT}/control/overrides/${config_name}/config"
  local target="/srv/dc/dc/${config_name}/config"

  if [[ -d "${source}" ]] && find "${source}" -mindepth 1 -print -quit | grep -q .; then
    append_service_header "${service}"
    printf '      - "%s:%s:ro"\n' "${source}" "${target}" >> "${OUTPUT_FILE}.tmp"
    MOUNT_COUNT=$((MOUNT_COUNT + 1))
  fi
}

load_env
seed_all_service_configs

if [[ -f "${GENERATE_SENSITIVE_CONFIGS_SCRIPT}" ]]; then
  bash "${GENERATE_SENSITIVE_CONFIGS_SCRIPT}" "${ENV_FILE}"
fi

declare -A EMITTED_SERVICES=()
MOUNT_COUNT=0

{
  printf '# Generated by generate-compose-overrides.sh. Do not edit by hand.\n'
  printf '# Each application config directory is bind-mounted from ${DEPLOY_ROOT}/control/overrides.\n'
  printf 'name: ${COMPOSE_PROJECT_NAME}\n'
  printf 'services:\n'
} > "${OUTPUT_FILE}.tmp"

append_config_dir_mount gateway GW
append_config_dir_mount loginsvr LoginSvr
append_config_dir_mount mdsvr MDSvr
append_config_dir_mount apssvr APSSvr
append_config_dir_mount quantsvr QuantSvr
append_config_dir_mount indsvr INDSvr
append_config_dir_mount simsvr SIMSvr
append_config_dir_mount batchsvr BatchSvr

if [[ "${MOUNT_COUNT}" -eq 0 ]]; then
  {
    printf '# Generated by generate-compose-overrides.sh. Do not edit by hand.\n'
    printf '# No config override directories were found under ${DEPLOY_ROOT}/control/overrides.\n'
    printf 'name: ${COMPOSE_PROJECT_NAME}\n'
    printf 'services: {}\n'
  } > "${OUTPUT_FILE}.tmp"
fi

mv -f "${OUTPUT_FILE}.tmp" "${OUTPUT_FILE}"
echo "Generated ${OUTPUT_FILE} with ${MOUNT_COUNT} config override directory mount(s)."
