-- Keep synchronized with dbscripts/DB/saas_tenant_control_plane_20260830.sql.
CREATE TABLE IF NOT EXISTS dc_tenant_application (
  application_id varchar(64) COLLATE utf8mb4_bin NOT NULL,
  request_id varchar(64) COLLATE utf8mb4_bin NOT NULL,
  tenant_code varchar(64) COLLATE utf8mb4_bin NOT NULL,
  organization_name varchar(255) NOT NULL,
  contact_name varchar(128) NOT NULL,
  contact_email varchar(255) NOT NULL,
  contact_phone varchar(64) DEFAULT NULL,
  use_case text,
  expected_users int unsigned NOT NULL DEFAULT 1,
  requested_symbols json DEFAULT NULL,
  requested_trial_days smallint unsigned NOT NULL DEFAULT 14,
  status varchar(24) NOT NULL DEFAULT 'PENDING',
  approved_location varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,
  review_comment varchar(1000) DEFAULT NULL,
  reviewer_id varchar(64) DEFAULT NULL,
  submitted_ip varchar(64) DEFAULT NULL,
  version bigint unsigned NOT NULL DEFAULT 1,
  create_time varchar(30) NOT NULL,
  update_time varchar(30) NOT NULL,
  review_time varchar(30) DEFAULT NULL,
  PRIMARY KEY (application_id),
  UNIQUE KEY uq_tenant_application_request (request_id),
  KEY idx_tenant_application_status_time (status, update_time),
  KEY idx_tenant_application_code (tenant_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SaaS tenant trial application';

CREATE TABLE IF NOT EXISTS dc_tenant (
  location varchar(64) COLLATE utf8mb4_bin NOT NULL,
  tenant_code varchar(64) COLLATE utf8mb4_bin NOT NULL,
  tenant_name varchar(255) NOT NULL,
  status varchar(24) NOT NULL DEFAULT 'TRIAL',
  registration_enabled tinyint(1) NOT NULL DEFAULT 1,
  admin_console_enabled tinyint(1) NOT NULL DEFAULT 1,
  trade_enabled tinyint(1) NOT NULL DEFAULT 1,
  domain_name varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  base_url varchar(500) NOT NULL,
  default_locale varchar(16) NOT NULL DEFAULT 'zh-CN',
  branding json DEFAULT NULL,
  quotas json DEFAULT NULL,
  trial_start_time varchar(30) DEFAULT NULL,
  trial_end_time varchar(30) DEFAULT NULL,
  source_application_id varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,
  create_by varchar(64) NOT NULL,
  update_by varchar(64) NOT NULL,
  create_time varchar(30) NOT NULL,
  update_time varchar(30) NOT NULL,
  PRIMARY KEY (location),
  UNIQUE KEY uq_tenant_code (tenant_code),
  UNIQUE KEY uq_tenant_domain (domain_name),
  UNIQUE KEY uq_tenant_application (source_application_id),
  KEY idx_tenant_status_trial_end (status, trial_end_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='SaaS tenant registry';

CREATE TABLE IF NOT EXISTS dc_tenant_symbol (
  location varchar(64) COLLATE utf8mb4_bin NOT NULL,
  security_id varchar(64) COLLATE utf8mb4_bin NOT NULL,
  market_indicator varchar(20) NOT NULL DEFAULT '4',
  enabled tinyint(1) NOT NULL DEFAULT 1,
  tick_size decimal(35,16) DEFAULT NULL,
  qty_tick_size decimal(35,16) DEFAULT NULL,
  min_order_qty decimal(35,16) DEFAULT NULL,
  max_order_qty decimal(35,16) DEFAULT NULL,
  min_notional decimal(35,16) DEFAULT NULL,
  market_take_bound decimal(18,10) DEFAULT NULL,
  max_price decimal(35,16) DEFAULT NULL,
  maker_commission decimal(18,10) DEFAULT NULL,
  taker_commission decimal(18,10) DEFAULT NULL,
  funding_interval int DEFAULT NULL,
  risk_tiers json DEFAULT NULL,
  create_by varchar(64) NOT NULL,
  update_by varchar(64) NOT NULL,
  create_time varchar(30) NOT NULL,
  update_time varchar(30) NOT NULL,
  PRIMARY KEY (location, security_id),
  KEY idx_tenant_symbol_enabled (location, enabled, security_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Tenant product and rule overrides';

CREATE TABLE IF NOT EXISTS dc_tenant_user_role (
  location varchar(64) COLLATE utf8mb4_bin NOT NULL,
  user_id varchar(64) COLLATE utf8mb4_bin NOT NULL,
  role_id varchar(64) COLLATE utf8mb4_bin NOT NULL,
  status varchar(24) NOT NULL DEFAULT 'ACTIVE',
  assigned_by varchar(64) NOT NULL,
  create_time varchar(30) NOT NULL,
  update_time varchar(30) NOT NULL,
  PRIMARY KEY (location, user_id, role_id),
  KEY idx_tenant_role_user (location, role_id, status, user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Tenant scoped RBAC membership';

CREATE TABLE IF NOT EXISTS dc_tenant_robot (
  location varchar(64) COLLATE utf8mb4_bin NOT NULL,
  robot_id varchar(64) COLLATE utf8mb4_bin NOT NULL,
  robot_name varchar(128) NOT NULL,
  security_id varchar(64) COLLATE utf8mb4_bin NOT NULL,
  api_user_id varchar(64) COLLATE utf8mb4_bin NOT NULL,
  api_key varchar(255) COLLATE utf8mb4_bin NOT NULL,
  quote_source varchar(32) NOT NULL DEFAULT 'APSSVR_INDEX',
  enabled tinyint(1) NOT NULL DEFAULT 0,
  bid_levels smallint unsigned NOT NULL DEFAULT 5,
  ask_levels smallint unsigned NOT NULL DEFAULT 5,
  level_spread_bps decimal(18,8) NOT NULL DEFAULT 5,
  level_step_bps decimal(18,8) NOT NULL DEFAULT 2,
  order_qty decimal(35,16) NOT NULL,
  max_position_qty decimal(35,16) NOT NULL,
  refresh_interval_ms int unsigned NOT NULL DEFAULT 1000,
  stale_price_ms int unsigned NOT NULL DEFAULT 5000,
  max_deviation_bps decimal(18,8) NOT NULL DEFAULT 100,
  circuit_breaker_seconds int unsigned NOT NULL DEFAULT 30,
  hedge_enabled tinyint(1) NOT NULL DEFAULT 0,
  hedge_venue varchar(64) DEFAULT NULL,
  hedge_account_ref varchar(255) DEFAULT NULL,
  strategy_config json DEFAULT NULL,
  runtime_status varchar(24) NOT NULL DEFAULT 'STOPPED',
  last_heartbeat_time varchar(30) DEFAULT NULL,
  create_by varchar(64) NOT NULL,
  update_by varchar(64) NOT NULL,
  create_time varchar(30) NOT NULL,
  update_time varchar(30) NOT NULL,
  PRIMARY KEY (location, robot_id),
  UNIQUE KEY uq_tenant_robot_symbol_name (location, security_id, robot_name),
  KEY idx_tenant_robot_enabled (location, enabled, security_id),
  KEY idx_tenant_robot_api (location, api_user_id, api_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Tenant scoped market making robot configuration';

CREATE TABLE IF NOT EXISTS dc_tenant_audit_log (
  audit_id varchar(64) COLLATE utf8mb4_bin NOT NULL,
  location varchar(64) COLLATE utf8mb4_bin NOT NULL,
  actor_id varchar(64) NOT NULL,
  actor_client_type varchar(24) DEFAULT NULL,
  action varchar(100) NOT NULL,
  resource_type varchar(64) NOT NULL,
  resource_id varchar(128) DEFAULT NULL,
  request_id varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,
  before_value json DEFAULT NULL,
  after_value json DEFAULT NULL,
  source_ip varchar(64) DEFAULT NULL,
  result varchar(24) NOT NULL,
  error_message varchar(1000) DEFAULT NULL,
  create_time varchar(30) NOT NULL,
  PRIMARY KEY (audit_id),
  KEY idx_tenant_audit_location_time (location, create_time),
  KEY idx_tenant_audit_actor_time (actor_id, create_time),
  KEY idx_tenant_audit_request (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Immutable tenant control-plane audit log';
