CREATE DATABASE IF NOT EXISTS dc
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS event
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

GRANT ALL PRIVILEGES ON dc.* TO 'dc'@'%';
GRANT ALL PRIVILEGES ON event.* TO 'dc'@'%';
FLUSH PRIVILEGES;
