server {
  listen 18096;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "same-origin" always;

  location = /healthz {
    default_type text/plain;
    return 200 'ok';
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
