##############################################################
# REGISTER config list
# Replace all placeholders before use.

REGISTER.ServerList=REGISTER.Svr1

REGISTER.Svr1.Name=REGISTER1
REGISTER.Svr1.Host={{REGISTRY_HOST}}:{{REGISTRY_PORT}}

NetType=dps
ProtoVersion=0

SERVER.MDSvr.Name=MDSvr
SERVER.MDSvr.Host={{PROD_HOST}}:{{MDSVR_PORT}}
SERVER.MDSvr.RegType=2
SERVER.MDSvr.RegisterEnable=1
SERVER.MDSvr.LBFactor=1
SERVER.MDSvr.ServiceName=MDSvr
SERVER.MDSvr.RegisterServerList=REGISTER.Svr1

SERVER.APSSvr.Name=APSSvr
SERVER.APSSvr.Host={{PROD_HOST}}:{{APSSVR_PORT}}
SERVER.APSSvr.RegType=2
SERVER.APSSvr.RegisterEnable=1
SERVER.APSSvr.LBFactor=1
SERVER.APSSvr.ServiceName=APSSvr
SERVER.APSSvr.RegisterServerList=REGISTER.Svr1

SERVER.QuantSvr.Name=QuantSvr
SERVER.QuantSvr.Host={{PROD_HOST}}:{{QUANTSVR_PORT}}
SERVER.QuantSvr.RegType=2
SERVER.QuantSvr.RegisterEnable=1
SERVER.QuantSvr.LBFactor=1
SERVER.QuantSvr.ServiceName=QuantSvr
SERVER.QuantSvr.RegisterServerList=REGISTER.Svr1

SERVER.INDSvr.Name=INDSvr
SERVER.INDSvr.Host={{PROD_HOST}}:{{INDSVR_PORT}}
SERVER.INDSvr.RegType=2
SERVER.INDSvr.RegisterEnable=1
SERVER.INDSvr.LBFactor=1
SERVER.INDSvr.ServiceName=INDSvr
SERVER.INDSvr.RegisterServerList=REGISTER.Svr1

SERVER.SIMSvr.Name=SIMSvr
SERVER.SIMSvr.Host={{PROD_HOST}}:{{SIMSVR_PORT}}
SERVER.SIMSvr.RegType=2
SERVER.SIMSvr.RegisterEnable=1
SERVER.SIMSvr.LBFactor=1
SERVER.SIMSvr.ServiceName=SIMSvr
SERVER.SIMSvr.RegisterServerList=REGISTER.Svr1

SERVER.BatchSvr.Name=BatchSvr
SERVER.BatchSvr.Host={{PROD_HOST}}:{{BATCHSVR_PORT}}
SERVER.BatchSvr.RegType=2
SERVER.BatchSvr.RegisterEnable=1
SERVER.BatchSvr.LBFactor=1
SERVER.BatchSvr.ServiceName=BatchSvr
SERVER.BatchSvr.RegisterServerList=REGISTER.Svr1
