# Replace all placeholders before use.
# Keep this file outside Git in real production.

CLICKHOUSE.DBCount=1
CLICKHOUSE.DBSourceName_0=ClickHouse1
CLICKHOUSE.DBUrl_0=jdbc:clickhouse://{{CLICKHOUSE_HOST}}:{{CLICKHOUSE_HTTP_PORT}}/{{CLICKHOUSE_DB_NAME}}?compression=true
CLICKHOUSE.DBUsername_0={{CLICKHOUSE_USERNAME}}
CLICKHOUSE.DBPasswd_0={{CLICKHOUSE_PASSWORD}}
CLICKHOUSE.DBIsEncrypt_0=false
CLICKHOUSE.DBMaxCount_0=50
CLICKHOUSE.DBMinCount_0=5
CLICKHOUSE.DBConnOutTime_0=1000
CLICKHOUSE.DBAsyncInsert_0=1
CLICKHOUSE.DBAsyncInsertMaxInternet_0=2000
