CREATE VIEW IF NOT EXISTS dc.quant_order_latest_view
(
    `quantID` String,
    `venueTypeGW` String,
    `securityID` String,
    `orderID` String,
    `tradeDate` Date32,
    `location` String,
    `marketIndicator` String,
    `clOrdID` String,
    `eventTime` String,
    `createTime` String,
    `updateTime` UInt64,
    `source` String,
    `userID` String,
    `userName` String,
    `algoName` String,
    `strategyName` String,
    `strategyVersion` String,
    `scene` String,
    `strategyPayload` String,
    `venues` String,
    `symbol` String,
    `execID` String,
    `ordStatus` String,
    `ordStatus2` String,
    `execType` String,
    `side` String,
    `ordType` String,
    `timeInForce` String,
    `positionSide` String,
    `settlType` String,
    `rejectText` String,
    `ordRejReason` String,
    `triggerType` String,
    `triggerPrice` String,
    `orderQty` Nullable(Decimal(38, 12)),
    `leavesQty` Nullable(Decimal(38, 12)),
    `cumQty` Nullable(Decimal(38, 12)),
    `price` Nullable(Decimal(38, 12)),
    `avgPx` Nullable(Decimal(38, 12)),
    `lastPx` Nullable(Decimal(38, 12)),
    `lastQty` Nullable(Decimal(38, 12)),
    `fee` Nullable(Decimal(38, 12)),
    `realizedPnl` Nullable(Decimal(38, 12)),
    `info1` String,
    `info2` String,
    `info3` String,
    `info4` String,
    `info5` String
)
AS SELECT
    quantID,
    venueTypeGW,
    securityID,
    orderID,
    argMax(tradeDate, versionTime) AS tradeDate,
    argMax(location, versionTime) AS location,
    argMax(marketIndicator, versionTime) AS marketIndicator,
    argMax(clOrdID, versionTime) AS clOrdID,
    argMax(eventTime, versionTime) AS eventTime,
    argMax(createTime, versionTime) AS createTime,
    max(versionTime) AS updateTime,
    argMax(source, versionTime) AS source,
    argMax(userID, versionTime) AS userID,
    argMax(userName, versionTime) AS userName,
    argMax(algoName, versionTime) AS algoName,
    argMax(strategyName, versionTime) AS strategyName,
    argMax(strategyVersion, versionTime) AS strategyVersion,
    argMax(scene, versionTime) AS scene,
    argMax(strategyPayload, versionTime) AS strategyPayload,
    argMax(venues, versionTime) AS venues,
    argMax(symbol, versionTime) AS symbol,
    argMax(execID, versionTime) AS execID,
    argMax(ordStatus, versionTime) AS ordStatus,
    argMax(ordStatus2, versionTime) AS ordStatus2,
    argMax(execType, versionTime) AS execType,
    argMax(side, versionTime) AS side,
    argMax(ordType, versionTime) AS ordType,
    argMax(timeInForce, versionTime) AS timeInForce,
    argMax(positionSide, versionTime) AS positionSide,
    argMax(settlType, versionTime) AS settlType,
    argMax(rejectText, versionTime) AS rejectText,
    argMax(ordRejReason, versionTime) AS ordRejReason,
    argMax(triggerType, versionTime) AS triggerType,
    argMax(triggerPrice, versionTime) AS triggerPrice,
    argMax(orderQty, versionTime) AS orderQty,
    argMax(leavesQty, versionTime) AS leavesQty,
    argMax(cumQty, versionTime) AS cumQty,
    argMax(price, versionTime) AS price,
    argMax(avgPx, versionTime) AS avgPx,
    argMax(lastPx, versionTime) AS lastPx,
    argMax(lastQty, versionTime) AS lastQty,
    argMax(fee, versionTime) AS fee,
    argMax(realizedPnl, versionTime) AS realizedPnl,
    argMax(info1, versionTime) AS info1,
    argMax(info2, versionTime) AS info2,
    argMax(info3, versionTime) AS info3,
    argMax(info4, versionTime) AS info4,
    argMax(info5, versionTime) AS info5
FROM
(
    SELECT *,
        updateTime AS versionTime
    FROM dc.quant_order
)
GROUP BY
    quantID,
    venueTypeGW,
    securityID,
    orderID;
