CREATE VIEW IF NOT EXISTS dc.quant_position_latest_view
(
    `location` String,
    `quantID` String,
    `venueTypeGW` String,
    `marketIndicator` String,
    `securityID` String,
    `positionSide` String,
    `tradeDate` Date32,
    `eventTime` String,
    `createTime` String,
    `updateTime` UInt64,
    `source` String,
    `userID` String,
    `accountID` String,
    `currency` String,
    `venues` String,
    `symbol` String,
    `positionType` String,
    `positionStatus` String,
    `demo` String,
    `leverage` Nullable(Decimal(38, 12)),
    `longPosition` Nullable(Decimal(38, 12)),
    `longAverage` Nullable(Decimal(38, 12)),
    `longUsedMargin` Nullable(Decimal(38, 12)),
    `longLiqPrice` Nullable(Decimal(38, 12)),
    `shortPosition` Nullable(Decimal(38, 12)),
    `shortAverage` Nullable(Decimal(38, 12)),
    `shortUsedMargin` Nullable(Decimal(38, 12)),
    `shortLiqPrice` Nullable(Decimal(38, 12)),
    `realizedPnl` Nullable(Decimal(38, 12)),
    `longLockedPosition` Nullable(Decimal(38, 12)),
    `shortLockedPosition` Nullable(Decimal(38, 12)),
    `bankruptcyPrice` Nullable(Decimal(38, 12)),
    `info1` String,
    `info2` String,
    `info3` String,
    `info4` String,
    `info5` String
)
AS SELECT
    location,
    quantID,
    venueTypeGW,
    marketIndicator,
    securityID,
    positionSide,
    argMax(tradeDate, versionTime) AS tradeDate,
    argMax(eventTime, versionTime) AS eventTime,
    argMax(createTime, versionTime) AS createTime,
    max(versionTime) AS updateTime,
    argMax(source, versionTime) AS source,
    argMax(userID, versionTime) AS userID,
    argMax(accountID, versionTime) AS accountID,
    argMax(currency, versionTime) AS currency,
    argMax(venues, versionTime) AS venues,
    argMax(symbol, versionTime) AS symbol,
    argMax(positionType, versionTime) AS positionType,
    argMax(positionStatus, versionTime) AS positionStatus,
    argMax(demo, versionTime) AS demo,
    argMax(leverage, versionTime) AS leverage,
    argMax(longPosition, versionTime) AS longPosition,
    argMax(longAverage, versionTime) AS longAverage,
    argMax(longUsedMargin, versionTime) AS longUsedMargin,
    argMax(longLiqPrice, versionTime) AS longLiqPrice,
    argMax(shortPosition, versionTime) AS shortPosition,
    argMax(shortAverage, versionTime) AS shortAverage,
    argMax(shortUsedMargin, versionTime) AS shortUsedMargin,
    argMax(shortLiqPrice, versionTime) AS shortLiqPrice,
    argMax(realizedPnl, versionTime) AS realizedPnl,
    argMax(longLockedPosition, versionTime) AS longLockedPosition,
    argMax(shortLockedPosition, versionTime) AS shortLockedPosition,
    argMax(bankruptcyPrice, versionTime) AS bankruptcyPrice,
    argMax(info1, versionTime) AS info1,
    argMax(info2, versionTime) AS info2,
    argMax(info3, versionTime) AS info3,
    argMax(info4, versionTime) AS info4,
    argMax(info5, versionTime) AS info5
FROM
(
    SELECT
        *,
        updateTime AS versionTime
    FROM dc.quant_position
)
GROUP BY
    location,
    quantID,
    venueTypeGW,
    marketIndicator,
    securityID,
    positionSide;
