CREATE VIEW IF NOT EXISTS dc.quant_account_balance_latest_view
(
    `location` String,
    `quantID` String,
    `venueTypeGW` String,
    `marketIndicator` String,
    `accountID` String,
    `currency` String,
    `positionType` String,
    `securityID` String,
    `tradeDate` Date32,
    `eventTime` String,
    `createTime` String,
    `updateTime` UInt64,
    `source` String,
    `userID` String,
    `venues` String,
    `accountStatus` String,
    `demo` String,
    `isTrader` String,
    `balance` Nullable(Decimal(38, 12)),
    `usedMargin` Nullable(Decimal(38, 12)),
    `wdBalance` Nullable(Decimal(38, 12)),
    `dayRealizedPnl` Nullable(Decimal(38, 12)),
    `holdRealizedPnl` Nullable(Decimal(38, 12)),
    `dayCommission` Nullable(Decimal(38, 12)),
    `freezedMargin` Nullable(Decimal(38, 12)),
    `freezedCommission` Nullable(Decimal(38, 12)),
    `freezedBalance` Nullable(Decimal(38, 12)),
    `info1` String,
    `info2` String,
    `info3` String,
    `info4` String,
    `info5` String
)
AS SELECT
    location,
    quantID,
    venueTypeGW,
    marketIndicator,
    accountID,
    currency,
    positionType,
    securityID,
    argMax(tradeDate, versionTime) AS tradeDate,
    argMax(eventTime, versionTime) AS eventTime,
    argMax(createTime, versionTime) AS createTime,
    max(versionTime) AS updateTime,
    argMax(source, versionTime) AS source,
    argMax(userID, versionTime) AS userID,
    argMax(venues, versionTime) AS venues,
    argMax(accountStatus, versionTime) AS accountStatus,
    argMax(demo, versionTime) AS demo,
    argMax(isTrader, versionTime) AS isTrader,
    argMax(balance, versionTime) AS balance,
    argMax(usedMargin, versionTime) AS usedMargin,
    argMax(wdBalance, versionTime) AS wdBalance,
    argMax(dayRealizedPnl, versionTime) AS dayRealizedPnl,
    argMax(holdRealizedPnl, versionTime) AS holdRealizedPnl,
    argMax(dayCommission, versionTime) AS dayCommission,
    argMax(freezedMargin, versionTime) AS freezedMargin,
    argMax(freezedCommission, versionTime) AS freezedCommission,
    argMax(freezedBalance, versionTime) AS freezedBalance,
    argMax(info1, versionTime) AS info1,
    argMax(info2, versionTime) AS info2,
    argMax(info3, versionTime) AS info3,
    argMax(info4, versionTime) AS info4,
    argMax(info5, versionTime) AS info5
FROM
(
    SELECT
        *,
        updateTime AS versionTime
    FROM dc.quant_account_balance
)
GROUP BY
    location,
    quantID,
    venueTypeGW,
    marketIndicator,
    accountID,
    currency,
    positionType,
    securityID;
