CREATE TABLE IF NOT EXISTS dc.quant_trade
(
    `id` String,
    `tradeDate` Date32,
    `eventTime` String,
    `createTime` String,
    `updateTime` UInt64,
    `source` String,
    `quantID` String,
    `userID` String,
    `userName` String,
    `algoName` String,
    `strategyName` String,
    `strategyVersion` String,
    `scene` String,
    `strategyPayload` String,
    `venueTypeGW` String,
    `venues` String,
    `location` String,
    `marketIndicator` String,
    `securityID` String,
    `symbol` String,
    `clOrdID` String,
    `orderID` String,
    `execID` String,
    `side` String,
    `ordType` String,
    `execType` String,
    `positionSide` String,
    `orderQty` Nullable(Decimal(38, 12)),
    `cumQty` Nullable(Decimal(38, 12)),
    `lastQty` Nullable(Decimal(38, 12)),
    `price` Nullable(Decimal(38, 12)),
    `avgPx` Nullable(Decimal(38, 12)),
    `lastPx` Nullable(Decimal(38, 12)),
    `fee` Nullable(Decimal(38, 12)),
    `realizedPnl` Nullable(Decimal(38, 12)),
    `info1` String,
    `info2` String,
    `info3` String,
    `info4` String,
    `info5` String
)
ENGINE = ReplacingMergeTree(updateTime)
PARTITION BY toYYYYMM(tradeDate)
ORDER BY (quantID, venueTypeGW, securityID, orderID, execID)
SETTINGS index_granularity = 8192;
