CREATE TABLE IF NOT EXISTS dc.quant_position
(
    `id` String,
    `tradeDate` Date32,
    `eventTime` String,
    `createTime` String,
    `updateTime` UInt64,
    `source` String,
    `quantID` String,
    `userID` String,
    `accountID` String,
    `currency` String,
    `venueTypeGW` String,
    `venues` String,
    `marketIndicator` String,
    `securityID` String,
    `symbol` String,
    `positionType` String,
    `positionStatus` String,
    `positionSide` String,
    `location` String,
    `demo` String,
    `leverage` Nullable(Decimal(38, 12)),
    `longPosition` Nullable(Decimal(38, 12)),
    `longAverage` Nullable(Decimal(38, 12)),
    `longUsedMargin` Nullable(Decimal(38, 12)),
    `longLiqPrice` Nullable(Decimal(38, 12)),
    `shortPosition` Nullable(Decimal(38, 12)),
    `shortAverage` Nullable(Decimal(38, 12)),
    `shortUsedMargin` Nullable(Decimal(38, 12)),
    `shortLiqPrice` Nullable(Decimal(38, 12)),
    `realizedPnl` Nullable(Decimal(38, 12)),
    `longLockedPosition` Nullable(Decimal(38, 12)),
    `shortLockedPosition` Nullable(Decimal(38, 12)),
    `bankruptcyPrice` Nullable(Decimal(38, 12)),
    `info1` String,
    `info2` String,
    `info3` String,
    `info4` String,
    `info5` String
)
ENGINE = ReplacingMergeTree(updateTime)
PARTITION BY cityHash64(location, quantID, venueTypeGW, marketIndicator, securityID, positionSide) % 16
ORDER BY (location, quantID, venueTypeGW, marketIndicator, securityID, positionSide)
SETTINGS index_granularity = 8192;
