CREATE TABLE IF NOT EXISTS dc.strategy_llm_call_log
(
    `id` String,
    `generation_task_id` String,
    `pipeline_run_id` String,
    `source_type` String,
    `source_ref` String,
    `provider` String,
    `model` String,
    `endpoint_url` String,
    `generation_engine` String,
    `call_stage` String,
    `call_seq` Int32,
    `retry_no` Int32,
    `strategy_name` String,
    `strategy_version` String,
    `parent_version` Nullable(String),
    `scene_hint` String,
    `generated_scene` String,
    `final_scene` String,
    `scene_confidence` Nullable(Float64),
    `scene_reason` String,
    `prompt_version` String,
    `template_version` String,
    `request_json` String,
    `response_json` String,
    `prompt_text` String,
    `response_text` String,
    `prompt_summary` String,
    `response_summary` String,
    `raw_usage_json` String,
    `input_tokens` Nullable(Int32),
    `output_tokens` Nullable(Int32),
    `total_tokens` Nullable(Int32),
    `cached_input_tokens` Nullable(Int32),
    `reasoning_tokens` Nullable(Int32),
    `prompt_cache_hit_tokens` Nullable(Int32),
    `prompt_cache_miss_tokens` Nullable(Int32),
    `estimated_cost_usd` Nullable(Float64),
    `http_status` Nullable(Int32),
    `status` String,
    `error_code` String,
    `error_message` String,
    `latency_ms` Nullable(Int64),
    `create_time` DateTime
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(create_time)
ORDER BY (generation_task_id, create_time, call_seq, id)
SETTINGS index_granularity = 8192;
